version: "3.7"

services:
  rocketchat:
    image: registry.rocket.chat/rocketchat/rocket.chat:6.0.0
    restart: unless-stopped
    volumes:
     - ./data/uploads:/app/uploads
    environment:
      MONGO_URL: "mongodb://mongodb:27017/rocketchat?replicaSet=rs0"
      MONGO_OPLOG_URL: "mongodb://mongodb:27017/local?replicaSet=rs0"
      ROOT_URL: "http://${ROCKETCHAT_HOST:-3000}:3000"
      PORT: 3000
    labels:
      traefik.enable: true
      traefik.http.routers.rocketchat.rule: Host(`${ROCKETCHAT_HOST}`)
      traefik.http.routers.rocketchat.tls: true
      traefik.http.routers.rocketchat.entrypoints: https
    depends_on:
      - mongodb

  mongodb:
    image: docker.io/bitnami/mongodb:5.0
    restart: unless-stopped
    volumes:
      - ./data/db:/bitnami/mongodb
    environment:
      MONGODB_REPLICA_SET_MODE: primary
      MONGODB_REPLICA_SET_NAME: rs0
      MONGODB_PORT_NUMBER: 27017
      MONGODB_INITIAL_PRIMARY_HOST: mongodb
      MONGODB_INITIAL_PRIMARY_PORT_NUMBER: 27017
      MONGODB_ADVERTISED_HOSTNAME: mongodb
      MONGODB_ENABLE_JOURNAL: true
      ALLOW_EMPTY_PASSWORD: yes

  synapse:
    image: docker.io/matrixdotorg/synapse:v1.78.0
    hostname: ${MATRIX_HOSTNAME}
    restart: unless-stopped
    environment:
      - SYNAPSE_SERVER_NAME=${MATRIX_HOSTNAME}
      - SYNAPSE_CONFIG_PATH=/data/homeserver.yaml
    volumes:
      - synapse_data:/data
    depends_on:
      - synapse_db
    labels:
      traefik.http.routers.synapse.rule: Host(`${MATRIX_HOSTNAME}`)
      traefik.http.routers.synapse.tls: true
      traefik.http.routers.synapse.entrypoints: https

  synapse_db:
    image: docker.io/postgres:14
    restart: unless-stopped
    volumes:
      - synapse_db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=synapse
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8 --lc-collate=C --lc-ctype=C
    labels:
      - "traefik.enable=false"

  traefik:
    image: docker.io/traefik:v2.6.1
    restart: unless-stopped
    ports:
     - 80:80
     - 443:443
     - ${ROCKETCHAT_PORT:-3000}:3000
     - ${MATRIX_PORT:-8008}:8008
     - ${TRAEFIK_DASHBOARD_PORT:-8080}:8080
    volumes:
      - ./config:/root/.config
      - ${DOCKER_SOCKET}:/var/run/docker.sock:ro

volumes:
  synapse_data:
  synapse_db_data:
